agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('<int:contact_id>', views.seeContact, name='view_contact'),

]

from .api import views as api_views

urlpatterns += [
    path('api/contacts/', api_views.ContactListCreateAPIView.as_view(), name='api_contacts'),
    path('api/contacts/<int:pk>/', api_views.ContactRetrieveAPIView.as_view(), name='api_contact_detail'),
]

contacts/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255)
    email = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    visible = models.BooleanField(default=True)
    photo = models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m')

    def __str__(self):
        return self.first_name

contacts/api/views.py
from rest_framework import generics
from ..models import Contact
from .serializers import ContactSerializer


class ContactListCreateAPIView(generics.ListCreateAPIView):
    queryset = Contact.objects.filter(visible=True).order_by('-id')
    serializer_class = ContactSerializer


class ContactRetrieveAPIView(generics.RetrieveAPIView):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer

contacts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Contact
from django.core.paginator import Paginator
from django.db.models import Q, Value
from django.db.models.functions import Concat
from django.contrib import messages


# Create your views here.

def index(request):
    contatos = Contact.objects.order_by('-id').filter(
        visible=True
    )
    paginator = Paginator(contatos, 5)

    page = request.GET.get('p')
    contatos = paginator.get_page(page)

    return render(request, 'contacts/index.html', {
        'contatos': contatos
    })


def seeContact(request, contact_id):
    contato = get_object_or_404(Contact, id=contact_id)
    return render(request, 'contacts/seeContact.html', {
        'contato': contato
    })


def search(request):
    termo = request.GET.get('termo')

    if termo is None or not termo:
        messages.add_message(
            request,
            messages.ERROR,
            'Search term cannot be empty.'
        )
        return redirect('contacts:index')

    campos = Concat('first_name', Value(' '), 'last_name')

    contatos = Contact.objects.annotate(
        full_name=campos
    ).filter(
        Q(full_name__icontains=termo)
    )

    paginator = Paginator(contatos, 5)

    page = request.GET.get('p')
    contatos = paginator.get_page(page)

    return render(request, 'contacts/search.html', {
        'contatos': contatos
    })

contatos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Contato
from django.core.paginator import Paginator
from django.db.models import Q, Value
from django.db.models.functions import Concat
from django.contrib import messages


# Create your views here.

def index(request):
    contatos = Contato.objects.order_by('-id').filter(
        mostrar=True
    )
    paginator = Paginator(contatos, 5)

    page = request.GET.get('p')
    contatos = paginator.get_page(page)

    return render(request, 'contatos/index.html', {
        'contatos': contatos
    })


def ver_contato(request, contato_id):
    contato = get_object_or_404(Contato, id=contato_id)
    return render(request, 'contatos/ver_contato.html', {
        'contato': contato
    })


def busca(request):
    termo = request.GET.get('termo')

    if termo is None or not termo:
        messages.add_message(
            request,
            messages.ERROR,
            'Campo termo não pode ficar vazio.'
        )
        return redirect('index')

    campos = Concat('nome', Value(' '), 'sobrenome')

    contatos = Contato.objects.annotate(
        nome_completo=campos
    ).filter(
        Q(nome_completo__icontains=termo)
    )

    paginator = Paginator(contatos, 5)

    page = request.GET.get('p')
    contatos = paginator.get_page(page)

    return render(request, 'contatos/busca.html', {
        'contatos': contatos
    })

contacts/templates/contacts/index.html
{% extends 'base.html' %}

{%block conteudo%}
  <h1 class="mt-5">My contacts</h1>

    <table class="table">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Phone</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
      {% for contato in contatos %}
        {%  if contato.visible %}
            <tr>
              <td>
                <a href="{% url 'contacts:view_contact' contato.id %}">{{ contato.first_name }}</a>
              </td>
              <td>{{ contato.last_name }}</td>
              <td>{{ contato.phone }}</td>
              <td>{{ contato.category }}</td>
            </tr>
        {% endif%}
      {% endfor %}
      </tbody>
    </table>

  <nav aria-label="Page navigation">
  <ul class="'pagination'">
    {% for pagina in contatos.paginator.page_range %}
        <a class="pagel-link" href="?p={{ pagina }}"> {{pagina}} </a>
    {% endfor %}
  </ul>
  </nav>

{%endblock%}

contacts/templates/contacts/search.html
{% extends 'base.html' %}

{%block conteudo%}
  <h1 class="mt-5">Search results</h1>

    <table class="table">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Phone</th>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
      {% for contato in contatos %}
        {%  if contato.visible %}
            <tr>
              <td>
                <a href="{% url 'contacts:view_contact' contato.id %}">{{ contato.first_name }}</a>
              </td>
              <td>{{ contato.last_name }}</td>
              <td>{{ contato.phone }}</td>
              <td>{{ contato.category }}</td>
            </tr>
        {% endif%}
      {% endfor %}
      </tbody>
    </table>

  <nav aria-label="Page navigation">
  <ul class="'pagination'">
    {% for pagina in contatos.paginator.page_range %}
        <a class="pagel-link" href="?p={{ pagina }}"> {{pagina}} </a>
    {% endfor %}
  </ul>
  </nav>

{%endblock%}

contacts/templates/contacts/seeContact.html
{% extends 'base.html' %}

{%block conteudo%}

  <h1 class="mt-5">{{ contato.first_name }} {{ contato.last_name }}</h1>

   {% if contato.photo %}
        <p>
          <img src="{{ contato.photo.url }}" style="max-width: 250px; height: auto;">
        </p>

    {% endif %}

        <dl>
          <dt>ID</dt>
          <dd>{{ contato.id }}</dd>

          <dt>Phone</dt>
          <dd>{{ contato.phone }}</dd>

          <dt>E-mail</dt>
          <dd>{{ contato.email }}</dd>

          <dt>Created at</dt>
          <dd>{{ contato.created_at|date:'d/m/Y H:i:m'  }}</dd>

          <dt>Category</dt>
          <dd>{{ contato.category }}</dd>

          <dt>Description</dt>
          <dd>
            {{ contato.description }}
          </dd>
        </dl>

{%endblock%}

contatos/templates/contatos/busca.html
{% extends 'base.html' %}

{%block conteudo%}
    <h1 class="mt-5">Minha agenda</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Sobrenome</th>
          <th>Telefone</th>
          <th>Categoria</th>
        </tr>
      </thead>
      <tbody>
      {% for contato in contatos %}
        {%  if contato.mostrar %}
            <tr>
              <td>
                <a href="{% url 'ver_contato' contato.id %}">{{ contato.nome }}</a>
              </td>
              <td>{{ contato.sobrenome }}</td>
              <td>{{ contato.telefone }}</td>
              <td>{{ contato.categoria }}</td>
            </tr>
        {% endif%}
      {% endfor %}
      </tbody>
    </table>

  <nav aria-label="Page navigation">
  <ul class="'pagination'">
    {% for pagina in contatos.paginator.page_range %}
        <a class="pagel-link" href="?p={{ pagina }}"> {{pagina}} </a>
    {% endfor %}
  </ul>
  </nav>

{%endblock%}

contatos/templates/contatos/index.html
{% extends 'base.html' %}

{%block conteudo%}
    <h1 class="mt-5">Minha agenda</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Sobrenome</th>
          <th>Telefone</th>
          <th>Categoria</th>
        </tr>
      </thead>
      <tbody>
      {% for contato in contatos %}
        {%  if contato.mostrar %}
            <tr>
              <td>
                <a href="{% url 'ver_contato' contato.id %}">{{ contato.nome }}</a>
              </td>
              <td>{{ contato.sobrenome }}</td>
              <td>{{ contato.telefone }}</td>
              <td>{{ contato.categoria }}</td>
            </tr>
        {% endif%}
      {% endfor %}
      </tbody>
    </table>

  <nav aria-label="Page navigation">
  <ul class="'pagination'">
    {% for pagina in contatos.paginator.page_range %}
        <a class="pagel-link" href="?p={{ pagina }}"> {{pagina}} </a>
    {% endfor %}
  </ul>
  </nav>

{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt">

<head>

  <title>Contacts</title>

  {% include 'parciais/_head.html' %}

</head>

<body>

{% include 'parciais/_nave.html' %}

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">

      <br><br>
  <form method="get" action="{% url 'contacts:search' %}">
        <div class="form-group row">
          <div class="col-12">
            <input class="form-control"
                   type="search" value="{{ request.GET.termo }}"
                   id="search-input"
                   placeholder="Type your search"
                   name="termo">
            {% if messages %}
            <br>
              {% for message in messages %}
              <div class="alert {{message.tags }}" role="'alert'">
                {{ message }}
              </div>
              {% endfor%}
            {% endif%}
          </div>
        </div>
      </form>

        {%block conteudo%} {%endblock%}
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.slim.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

templates/parciais/_nave.html
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
  <a class="navbar-brand" href="{% url 'contacts:index' %}">Contacts</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>